-- MySQL Script generated by MySQL Workbench
-- Thu Feb 16 20:18:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema titos_market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema titos_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titos_market` DEFAULT CHARACTER SET utf8 ;
USE `titos_market` ;

-- -----------------------------------------------------
-- Table `titos_market`.`tbl_situcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titos_market`.`tbl_situcoes` (
  `idSituacao` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSituacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `titos_market`.`tbl_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titos_market`.`tbl_categorias` (
  `idCategoria` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `visibilidade` CHAR(1) NULL DEFAULT '1',
  `id_situacao` INT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ) VISIBLE,
  INDEX `id_situacao_idx` (`id_situacao` ASC) VISIBLE,
  CONSTRAINT `id_situacao`
    FOREIGN KEY (`id_situacao`)
    REFERENCES `titos_market`.`tbl_situcoes` (`idSituacao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
